### ISSUE TITLE
how to run with a netcore api program

### ISSUE THREAD

**Issue by lengyjc** [database-mesh/pisanix#113]
how to run with a netcore api program ,I have used the Deployment of K8S, other steps are according to the document, the startup of the sidecar reported an error, can I only start through helm?

error full info:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `admin`", line: 1, column: 301) }', app/config/src/config.rs:132:46 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by mlycore** [comment]
Thanks for your feedback. You could add some annotations to VirtualDatabase, then restart the aplication Pod. Examples:
```yaml
apiVersion: core.database-mesh.io/v1alpha1
kind: VirtualDatabase
metadata:
  annotations:
    database-mesh.io/metrics-port: "9090" # add this annotation
  name: catalogue
spec:
  services:
  - databaseMySQL:
      db: socksdb
      host: 127.0.0.1
      password: fake_password
      poolSize: 3
      port: 3306
      user: root
    name: my_mysql
    trafficStrategy: catalogue
```
