### ISSUE TITLE
Pisa-Proxy supports generic route rule in read write splitting

### ISSUE THREAD

**Issue by wbtlb** [database-mesh/pisanix#227]
## Feature Request

# Background
Pisa-Proxy has supported `static` and `dynamic` read write splitting.The route rule is based on `regex`.Pisa-Proxy should provides a generic route rule to route SQL without regex.

# Implement
## Description
In Pisa-Proxy we could config regex rule to match different rule to route to different backend.Now, user can config a generic rule to route SQL.If user config regex rule and generic rule at the same time, Pisa-Proxy shoud match with regex firstly.If the rule is not hinted, SQL will be routed to default backend.

### Toml configuration example
```toml
[proxy.config.read_write_splitting]

[proxy.config.read_write_splitting.static]
default_target = "read"

# generic rule match
[[proxy.config.read_write_splitting.static.rule]]
name = "generic-rule"
type = "generic"
algorithm_name = "random"

# base on regex rule match
[[proxy.config.read_write_splitting.static.rule]]
name = "read-rule"
type = "generic"
regex = ["^select"]
target = "read"
algorithm_name = "random"
```

# Develoment Task
- [x] support generic configuration
- [x] add generic rule
