### ISSUE TITLE
PisaProxy will crash even it has env variables about ADMIN

### ISSUE THREAD

**Issue by mlycore** [database-mesh/pisanix#317]
### What version of Pisanix are you using?

v0.2.0

### What operating system and CPU are you using?

n/a

### Steps to reproduce

If any application was injected with PisaProxy, but no VirtualDatabase was bounded, the PisaProxy log showed it was crashing without `admin` config.

```shell
# k logs catalogue-6c66768c75-d5p4g -n demotest -c pisa-proxy
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `admin`", line: 1, column: 277) }', app/config/src/config.rs:221:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```yaml
  - args:
    - sidecar
    env:
    - name: PISA_CONTROLLER_SERVICE
      value: pisa-controller
    - name: PISA_CONTROLLER_NAMESPACE
      value: pisa-system
    - name: PISA_DEPLOYED_NAMESPACE
      value: demotest
    - name: PISA_DEPLOYED_NAME
      value: catalogue
    - name: PISA_PROXY_ADMIN_LISTEN_HOST
      value: 0.0.0.0
    - name: PISA_PROXY_ADMIN_LISTEN_PORT
      value: "5591"
    - name: PISA_PROXY_ADMIN_LOG_LEVEL
      value: INFO
    image: pisanixio/proxy:v0.2.0
    imagePullPolicy: IfNotPresent
    name: pisa-proxy
```

### What did you expect?

PisaProxy builds configs from env variables rather than crash

### What did happened?

PisaProxy ignored the env variables and then crashed.
